<?php

namespace app\components;
use yii\base\Widget;

class MyWidget extends Widget
{
    public $name;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
//        if ($this->name === null) $this->name = 'Гость'; // параметр в виджет
        ob_start();
    }

    public function run()
    {
//        return "<h2>{$this->name}, Hello World!</h2>";
//        return $this->render('my', ['name' => $this->name]);// добавление переменной
        $content = ob_get_clean();
        $content = mb_strtoupper( $content, 'UTF-8' );
        return $this->render('my', compact('content'));
    }
}